MODULE = MTEST-PC-JCAE
export MODULE

build:

clean:

install: build
	swit -V -ioc MTEST-PC-JCAE

help:
	@echo "The following targets are available with this Makefile:-"
	@echo "make (calls default target)"
	@echo "make build (default)"
	@echo "make install"
	@echo "make clean"
	@echo "make help"
